### ISSUE TITLE
Enum documentation

### ISSUE THREAD

**Issue by MatthewScholefield** [nicholishen/tooldantic#3]
Great library! So whenever using Enums, I found there's no way to document individual enum values which is a painpoint. I'm wondering if you had any ideas about that.

Here's what I initially tried:

```python
from enum import Enum
from typing import Any, Dict
from pydantic_core import CoreSchema, core_schema
from pydantic import GetJsonSchemaHandler, BaseModel, Field


class DocumentedEnum(str, Enum):
    def __new__(cls, value: str, doc: str):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.__doc__ = doc
        return obj


class JsonDocumentedEnum(DocumentedEnum):
    @classmethod
    def __get_pydantic_core_schema__(cls, source_type, handler):
        enum_values = [member.value for member in cls]
        return core_schema.literal_schema(enum_values)

    @classmethod
    def __get_pydantic_json_schema__(
        cls, core_schema: CoreSchema, handler: GetJsonSchemaHandler
    ) -> Dict[str, Any]:
        json_schema = handler(core_schema)
        json_schema = handler.resolve_ref_schema(json_schema)
        json_schema['oneOf'] = [
            {'const': member.value, 'description': member.__doc__ or ''}
            for member in cls
        ]
        json_schema.pop('enum', None)
        return json_schema
```

This embeds documentation by representing enums as a `oneOf` with a list of constants with descriptions, BUT then I realized OpenAI doesn't support `oneOf` :joy:.

So I ended up just incorporating the `.__doc__` values into the field description of places the enum is used:

```python

class ProjectLabel(DocumentedEnum):
    PYTHON_CLI = 'python', 'The user is asking to create a Python command line program / script / library / backend'
    REACT_FRONTEND = 'react', 'The user specifically mentions wanting to build a frontend using React'

class AnnotationResult(BaseModel):
    """Some attributes documenting what the user asked for"""
    ...
    project_labels: List[ProjectLabel] = Field(..., description='A series of labels (if any) annotating the various attributes of the project the user asked to create. Possible values: {value_desc}'.format(
        value_desc=', '.join(f'{v.value} ({v.__doc__})' for v in ProjectLabel)
    ))

**Comment by nicholishen** [comment]
Thanks for bringing this up! As you’ve noticed, Pydantic handles Enums similarly to Literals when it comes to JSON schema. This means there’s no direct way to document individual enum values in the schema.

One way to work around this is by including the descriptions for the enum values directly in the field’s description. That way, all the relevant information is still available in the schema.

Here’s an example of how you could do it:

```python
from enum import Enum
from typing import List
from pydantic import BaseModel, Field

class ProjectLabel(str, Enum):
    PYTHON_CLI = 'python'
    REACT_FRONTEND = 'react'
    NONE = 'none'

class AnnotationResult(BaseModel):
    """
    Describes what the user requested for the project.
    """
    project_labels: List[ProjectLabel] = Field(
        ...,
        description=(
            "Labels describing the project attributes. Possible values:\n"
            "- 'python': User wants to create a Python command-line tool or library.\n"
            "- 'react': User mentions building a React frontend.\n"
            "- 'none': No specific project type mentioned."
        )
    )
```

Another option is to use the enum's docstring and reference it in the field description:

```python
from enum import Enum
from typing import List
from pydantic import BaseModel, Field

class ProjectLabel(str, Enum):
    """
    Project labels:
    - 'python': User wants to create a Python command-line tool or library.
    - 'react': User mentions building a React frontend.
    - 'none': No specific project type mentioned.
    """
    PYTHON_CLI = 'python'
    REACT_FRONTEND = 'react'
    NONE = 'none'

class AnnotationResult(BaseModel):
    project_labels: List[ProjectLabel] = Field(
        ...,
        description=ProjectLabel.__doc__
    )
```

This way, you can still include detailed descriptions of the enum values in the JSON schema, even if the schema itself doesn’t directly support it.

Hope this helps! Let me know if you have any other questions or need more info.

**Comment by MatthewScholefield** [comment]
Thanks for sharing your approaches! Basically I just wanted to brainstorm if there was a better solution that could be provided within the library. For example, the `DocumentedEnum` could be incorporated into the library with a helper `.field_description(...)` class method that appends the list of formatted calue docstrings to the description.

Right now though I don't think there's enough use cases to generalize, but something to think about.

**Comment by nicholishen** [comment]
Oh, I see what you're saying now. Yeah, I like the idea. How about something like this? 
```
import json
from enum import Enum

from tooldantic import GenericBaseModel


class DescribedEnum(str, Enum):
    def __new__(cls, value, description):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.description = description
        return obj

    @classmethod
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        docstring = "The available options are:\n"
        for member in cls:
            docstring += f"'{member.value}': {member.description}\n"
        cls.__doc__ = docstring

# Test Enum using DescribedEnum base class


class Status(DescribedEnum):
    SUCCESS = "SUCCESS", "Operation completed successfully."
    ERROR = "ERROR", "Operation failed."
    NOT_FOUND = "NOT_FOUND", "Resource not found."


# Can be used like a normal Enum
assert Status.SUCCESS == "SUCCESS"


class Tool(GenericBaseModel):
    """Use this tool to manage statuses."""
    status: list[Status]


print(json.dumps(Tool.model_json_schema(), indent=2))

# {
#   "name": "Tool",
#   "description": "Use this tool to manage statuses.",
#   "parameters": {
#     "type": "object",
#     "properties": {
#       "status": {
#         "type": "array",
#         "items": {
#           "type": "string",
#           "description": "The available options are:\n'SUCCESS': Operation completed successfully.\n'ERROR': Operation failed.\n'NOT_FOUND': Resource not found.",
#           "enum": [
#             "SUCCESS",
#             "ERROR",
#             "NOT_FOUND"
#           ]
#         }
#       }
#     },
#     "required": [
#       "status"
#     ]
#   }
# }
```

**Comment by MatthewScholefield** [comment]
Ooh that's perfect!

**Comment by MatthewScholefield** [comment]
Btw, I made two improvements:

```python
class DocumentedEnum(str, Enum):
    def __new__(cls, value, description):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.__doc__ = description
        return obj

    @classmethod
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        doc_fmt = cls.__doc__ or ''
        if not '{options}' in doc_fmt:
            if doc_fmt:
                doc_fmt = doc_fmt.rstrip('.') + '. '
            doc_fmt = doc_fmt + 'Valid options: {options}'
        cls.__doc__ = doc_fmt.format(
            options="\n".join(
                f"'{member.value}': {member.__doc__}" for member in cls
            )
        )
```

This lets you write:
```python
class Status(DocumentedEnum):
    """Return status for operation. Possible values: {options}"""
    SUCCESS = "SUCCESS", "Operation completed successfully."
    ERROR = "ERROR", "Operation failed."
    NOT_FOUND = "NOT_FOUND", "Resource not found."
```

Notably:
 - Use `obj.__doc__` for per-enum description since otherwise type analyzer complains (and `__doc__` seems reasonable IMO)
 - Use the original docstring of the enum for the template string, if it exists. Also allow for including original docstring as a prefix if it doesn't contain the template value

**Comment by nicholishen** [comment]
What do you think about fool-proofing it a bit since there will only ever be one arg passed to format? 
```python
class DocumentedEnum(str, Enum):
    """
    DocumentedEnum is a subclass of str and Enum that allows for the creation of enumerations with associated descriptions.
    It also automatically generates a formatted class-level docstring that includes all valid options and their descriptions.
    Example:
        Define a new enumeration with descriptions and a templatized docstring:
        ```python
        class Status(DocumentedEnum):
            '''Return status for operation. Possible values:\n{options}'''
            SUCCESS = "SUCCESS", "Operation completed successfully."
            ERROR = "ERROR", "Operation failed."
            NOT_FOUND = "NOT_FOUND", "Resource not found."
        print(Status.__doc__)
        ```
        This will output:
        ```
        Return status for operation. Possible values:
        'SUCCESS': Operation completed successfully.
        'ERROR': Operation failed.
        'NOT_FOUND': Resource not found.
        ```
    """
    def __new__(cls, value, description):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.__doc__ = description
        return obj

    @classmethod
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)

        doc_fmt = cls.__doc__ or ''
        pattern = re.compile(r"\{.*?\}")
        if pattern.search(doc_fmt):
            doc_fmt = pattern.sub("{0}", doc_fmt)
        else:
            doc_fmt += '\n\nValid options:\n{0}'
        cls.__doc__ = doc_fmt.format(
            "\n".join(
                f"'{member.value}': {member.__doc__}" for member in cls
            )
        )


```

**Comment by MatthewScholefield** [comment]
Nice! For consistency though I wonder if it should error if there's a different label and/or if there should be only one way of specifying it (ie. maybe only `{}` or `{0}`).

Anyways, the difference is trivial imo and either way lgtm 👍.

**Comment by nicholishen** [comment]
Fair. Although I like (not married to) the idea of allowing the dev to use the docstring as both a way to document the code and supply descriptions to the LLM. I could anticipate an issue arising if dev makes a docstring template with more than 2 placeholders but in that case, we could raise an exception.

```
class DocumentedEnum(str, Enum):
    """
    DocumentedEnum is a subclass of str and Enum that allows for the creation of enumerations with associated descriptions.
    It also automatically generates a formatted class-level docstring that includes all valid options and their descriptions.
    Example:
        Define a new enumeration with descriptions and a templatized docstring:
        ```python
        class Status(DocumentedEnum):
            '''Return status for operation. Possible values:\n{options}'''
            SUCCESS = "SUCCESS", "Operation completed successfully."
            ERROR = "ERROR", "Operation failed."
            NOT_FOUND = "NOT_FOUND", "Resource not found."
        print(Status.__doc__)
        ```
        This will output:
        ```
        Return status for operation. Possible values:
        'SUCCESS': Operation completed successfully.
        'ERROR': Operation failed.
        'NOT_FOUND': Resource not found.
        ```
    """
    def __new__(cls, value, description):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.__doc__ = description
        return obj

    @classmethod
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)

        doc_fmt = cls.__doc__ or ''
        pattern = re.compile(r"\{.*?\}")
        placeholders = pattern.findall(doc_fmt)
        if len(placeholders) > 1:
            raise ValueError(
                f"Only one placeholder is allowed for enum options in the `{cls.__name__}` docstring. "
                f"Found {len(placeholders)} in '{doc_fmt}'"
            )
        if placeholders:
            doc_fmt = pattern.sub("{0}", doc_fmt)
        else:
            doc_fmt += '\n\nValid options:\n{0}'
        cls.__doc__ = doc_fmt.format(
            "\n".join(
                f"'{member.value}': {member.__doc__}" for member in cls
            )
        )

```
This way, the template placeholder could be documented by dev in any way they please. eg. `{}`, `{0}`, `{any_identifier}`

Thanks for all your help on this improvement. Would you like to submit a pull request so you can get credit for your contribution?
